# Generated by Django 4.0.6 on 2022-07-18 10:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('popular_post_managers', django.db.models.manager.Manager()),
            ],
        ),
    ]
